### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by ucdavis95616** [pytorch/java-demo#23]
```
(base) root@login02:java-demo$ ./gradlew run

> Task :run FAILED
Exception in thread "main" java.lang.NoSuchMethodError: Method org.pytorch.NativePeer.initHybrid(Ljava/lang/String;Ljava/util/Map;I)Lcom/facebook/jni/HybridData; not found
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
        at java.base/java.lang.System.loadLibrary(System.java:1902)
        at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:22)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
        at org.pytorch.NativePeer.<clinit>(NativePeer.java:11)
        at org.pytorch.Module.load(Module.java:23)
        at demo.App.main(App.java:11)
```

**Comment by m416kar98k** [comment]
below 1.4.0 and above 1.6.0 includes 1.6.0 is not working

**Comment by m416kar98k** [comment]
stuck on executing

**Comment by dreiss** [comment]
Can you try with the latest release and tell me if you're still seeing this?  Please make sure that the version of libtorch that you've downloaded matches the jar that you're using.
